---
- hosts: asanova_gcp_ggr
  gather_facts: true
  vars:
    grid_router_regions:
      - name: "region-1"
        hosts:
          - name: 35.237.116.255
            port: 4444
            browser_count: 3
          - name: 35.196.111.33
            port: 4444
            browser_count: 3
  roles:
    - geerlingguy.docker
    - robertdebock.python_pip
    - { role: ../gridrouter-docker }