---
- hosts: maxver_gcp_ggr-2
  gather_facts: true
  vars:
    grid_router_regions:
      - name: "region-1"
        hosts:
          - name: 34.74.127.182
            port: 4444
            browser_count: 3
          - name: 34.74.96.194
            port: 4444
            browser_count: 3
  roles:
    - geerlingguy.docker
    - robertdebock.python_pip
    - { role: ../gridrouter-docker }